version: "3.5"

services:
  backend:
    container_name: 'backend-lengoo'
    build: ./
    ports:
      - "8080:8080"
      - "8090:8090"
    links:
      - "mongo"
      - "mongo-express"
      - "redis"
      - "rabbitmq"
      # - "elk"
    volumes:
      - .:/usr/src/app
    depends_on:
      - "mongo"
      - "mongo-express"
      - "redis"
      - "rabbitmq"
      # - "elk"


  mongo:
    image: mongo:latest
    container_name: 'mongodb-lengoo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes: 
      - ./users_init.sh:/docker-entrypoint-initdb.d/users_init.sh:ro
    ports:
      - '27017:27017'
    expose:
      - '27017'

  mongo-express:
    image: mongo-express:latest
    container_name: 'mongoExpress-lengoo'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    depends_on:
      - mongo

  # elk:
  #   image: sebp/elk
  #   container_name: 'elk-lengoo'
  #   ports:
  #     - "5601:5601"
  #     - "9200:9200"
  #     - "5044:5044"

  redis:
    container_name: 'redis-lengoo'
    image: 'redis'
    ports:
      - '6379:6379'

  rabbitmq:
    container_name: 'rabbitmq-lengoo'
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'



volumes: 
  mongodb-data:
  esdata:
    driver: local